name = "pixelpeak-api"
main = "src/index.js"
compatibility_date = "2024-11-06"
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "340c0067938145998530c9f0a17b613a"

[vars]
PBKDF2_ITERATIONS = "10000"
