name = "pixelpeak-api"
main = "src/index.js"
compatibility_date = "2024-11-06"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "pixelpeak"
database_id = "REPLACE_WITH_D1_ID"

[vars]
PBKDF2_ITERATIONS = "10000"
